### ISSUE TITLE
How to build and deploy the engine | pio build

### ISSUE THREAD

**Issue by bloodymind** [PredictionIO/template-scala-parallel-similarproduct#10]
Dear all ,

I have build the apps. i tried `pio build` and i always got this :

```
[INFO] [Console$] Using existing engine manifest JSON at /Applications/XAMPP/xamppfiles/htdocs/MySimilarProduct/manifest.json
[INFO] [Console$] Using command '/Users/Soufiane/PredictionIO/sbt/sbt' at the current working directory to build.
[INFO] [Console$] If the path above is incorrect, this process will fail.
[INFO] [Console$] Uber JAR disabled. Making sure lib/pio-assembly-0.9.5.jar is absent.
[INFO] [Console$] Going to run: /Users/Soufiane/PredictionIO/sbt/sbt  package assemblyPackageDependency
[ERROR] [Console$] Return code of previous step is 1. Aborting.
````

Maybe I missed something in the documention  ? or maybe an issue ? There is any solution ?
Thanks in advance.
( Sorry  i'm newbie ).

**Comment by k4hoo** [comment]
@bloodymind , please try "pio build --verbose" to get more info of the error

**Comment by bloodymind** [comment]
Well i tried that too , still get that issue : 
```
[INFO] [Console$] Using existing engine manifest JSON at /Applications/XAMPP/xamppfiles/htdocs/MySimilarProduct/manifest.json
[INFO] [Console$] Using command '/Users/Soufiane/PredictionIO/sbt/sbt' at the current working directory to build.
[INFO] [Console$] If the path above is incorrect, this process will fail.
[INFO] [Console$] Uber JAR disabled. Making sure lib/pio-assembly-0.9.5.jar is absent.
[INFO] [Console$] Going to run: /Users/Soufiane/PredictionIO/sbt/sbt  package assemblyPackageDependency
[ERROR] [Console$] Could not find launcher jar: /Users/Soufiane/PredictionIO/bin/sbt-launch.jar
[ERROR] [Console$] Return code of previous step is 2. Aborting.
````

But now it solved ! if you see in list of the errors , there is `sbt-launch.jar`missing file , i tried to download it ( i mean sbt ) from their website , and boom it works.

Maybe those files are missing because i missed something in documentation ?

( PS : The status of the issue if solved as i mentioned  )

**Comment by pankaj9492** [comment]
Hi all, i am facing same problem, when i am runing this command as you told above:
_pio build --verbose_  got below errors, how would be resolved?
parse@parse:/var/www/PredictionIO-0.9.6/template/k2$ /var/www/PredictionIO-0.9.6/bin/pio build --verbose
[INFO] [Console$] Using existing engine manifest JSON at /var/www/PredictionIO-0.9.6/template/k2/manifest.json
[INFO] [Console$] Using command '/var/www/PredictionIO-0.9.6/sbt/sbt' at the current working directory to build.
[INFO] [Console$] If the path above is incorrect, this process will fail.
[INFO] [Console$] Uber JAR disabled. Making sure lib/pio-assembly-0.9.6.jar is absent.
[INFO] [Console$] Going to run: /var/www/PredictionIO-0.9.6/sbt/sbt  package assemblyPackageDependency
[INFO] [Console$] Getting org.scala-sbt sbt 0.13.7 ...
[DEBUG] [UpgradeCheckRunner] Update metainfo not found. https://direct.prediction.io/0.9.6/build/ebctech.ECommerceRecommendationEngine.json
[INFO] [Console$]
[INFO] [Console$] :: problems summary ::
[INFO] [Console$] :::: WARNINGS
[INFO] [Console$]               module not found: org.scala-sbt#sbt;0.13.7
[INFO] [Console$]
[INFO] [Console$]       ==== local: tried
[INFO] [Console$]
[INFO] [Console$]         /home/parse/.ivy2/local/org.scala-sbt/sbt/0.13.7/ivys/ivy.xml
[INFO] [Console$]
[INFO] [Console$]         -- artifact org.scala-sbt#sbt;0.13.7!sbt.jar:
[INFO] [Console$]
[INFO] [Console$]         /home/parse/.ivy2/local/org.scala-sbt/sbt/0.13.7/jars/sbt.jar
[INFO] [Console$]
[INFO] [Console$]       ==== typesafe-ivy-releases: tried
[INFO] [Console$]
[INFO] [Console$]         https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.7/ivys/ivy.xml
[INFO] [Console$]
[INFO] [Console$]       ==== Maven Central: tried
[INFO] [Console$]
[INFO] [Console$]         https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.7/sbt-0.13.7.pom
[INFO] [Console$]
[INFO] [Console$]         -- artifact org.scala-sbt#sbt;0.13.7!sbt.jar:
[INFO] [Console$]
[INFO] [Console$]         https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.7/sbt-0.13.7.jar
[INFO] [Console$]
[INFO] [Console$]               ::::::::::::::::::::::::::::::::::::::::::::::
[INFO] [Console$]
[INFO] [Console$]               ::          UNRESOLVED DEPENDENCIES         ::
[INFO] [Console$]
[INFO] [Console$]               ::::::::::::::::::::::::::::::::::::::::::::::
[INFO] [Console$]
[INFO] [Console$]               :: org.scala-sbt#sbt;0.13.7: not found
[INFO] [Console$]
[INFO] [Console$]               ::::::::::::::::::::::::::::::::::::::::::::::
[INFO] [Console$]
[INFO] [Console$]
[INFO] [Console$] :::: ERRORS
[INFO] [Console$]       Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.7/ivys/ivy.xml
[INFO] [Console$]
[INFO] [Console$]
[INFO] [Console$] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[INFO] [Console$] unresolved dependency: org.scala-sbt#sbt;0.13.7: not found
[INFO] [Console$] Error during sbt execution: Error retrieving required libraries
[INFO] [Console$]   (see /home/parse/.sbt/boot/update.log for complete log)
[INFO] [Console$] Error: Could not retrieve sbt 0.13.7
[ERROR] [Console$] Return code of previous step is 1. Aborting.

**Comment by bloodymind** [comment]
@pankaj9492 ,

Please check your JAVA environnement , i had the same issue , i've had installed Java 8 to solve it.
- Try to type echo $JAVA_HOME to see if its return anything 
- Install the missing *.jar files

Good luck.

**Comment by pankaj9492** [comment]
Hi, 
Thanks for this support, I have checked both things. it is ok but still getting same error.

..................>[INFO] [Console$]       Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.7/ivys/ivy.xml
[INFO] [Console$]
[INFO] [Console$]
[INFO] [Console$] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[INFO] [Console$] unresolved dependency: org.scala-sbt#sbt;0.13.7: not found
[INFO] [Console$] Error during sbt execution: Error retrieving required libraries
[INFO] [Console$]   (see /home/parse/.sbt/boot/update.log for complete log)
[INFO] [Console$] Error: Could not retrieve sbt 0.13.7
[ERROR] [Console$] Return code of previous step is 1. Aborting.
parse@parse:/var/www/PredictionIO-0.9.6/template/k2$ **java -version**
**_java version "1.8.0_77"_**
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
parse@parse:/var/www/PredictionIO-0.9.6/template/k2$ **echo $JAVA_HOME**
**_/usr/lib/jvm/java-8-oracle/jre_**
parse@parse:/var/www/PredictionIO-0.9.6/template/k2$

so now what can i do plz suggest!

**Comment by pankaj9492** [comment]
I have resolved above issue but now i am facing another error plz have look and help ,

"[INFO] [Console$]       at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[INFO] [Console$]       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] [Console$]       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] [Console$]       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] [Console$]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] [Console$]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] [Console$]       at java.lang.Thread.run(Thread.java:745)
_**[INFO] [Console$] [error] (*:update) sbt.ResolveException: unresolved dependency: com.twitter#chill_2.10;0.7.2: not found
[INFO] [Console$] [error] unresolved dependency: com.twitter#chill-bijection_2.10;0.7.2: not found
[INFO] [Console$] [error] unresolved dependency: com.twitter#chill-java;0.5.0: not found
[INFO] [Console$] [error] unresolved dependency: com.twitter#parquet-column;1.6.0rc3: not found
[INFO] [Console$] [error] unresolved dependency: com.twitter#parquet-hadoop;1.6.0rc3: not found
[INFO] [Console$] [error] Total time: 94 s, completed May 30, 2016 8:33:32 AM**_
[ERROR] [Console$] Return code of previous step is 1. Aborting.
"

**Comment by glsravya** [comment]
Hi,
I am facing compilation errors in building this engine. Below is the trace. I am new to predictionIo as well as scala. Could you please help me in fixing it.

Compiling 6 Scala sources to /Users/.../MySimilarProduct/target/scala-2.10/classes...
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/ALSAlgorithm.scala:1: '{' expected but identifier found.
[INFO] [Console$] [error] package incubator-predictionio-template-similar-product
[INFO] [Console$] [error]                  ^
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/ALSAlgorithm.scala:238: '}' expected but eof found.
[INFO] [Console$] [error] }
[INFO] [Console$] [error]  ^
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/CooccurrenceAlgorithm.scala:1: '{' expected but identifier found.
[INFO] [Console$] [error] package incubator-predictionio-template-similar-product
[INFO] [Console$] [error]                  ^
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/CooccurrenceAlgorithm.scala:158: '}' expected but eof found.
[INFO] [Console$] [error] }
[INFO] [Console$] [error]  ^
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/DataSource.scala:1: '{' expected but identifier found.
[INFO] [Console$] [error] package incubator-predictionio-template-similar-product
[INFO] [Console$] [error]                  ^
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/DataSource.scala:113: '}' expected but eof found.
[INFO] [Console$] [error] }
[INFO] [Console$] [error]  ^
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/Engine.scala:1: '{' expected but identifier found.
[INFO] [Console$] [error] package incubator-predictionio-template-similar-product
[INFO] [Console$] [error]                  ^
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/Engine.scala:35: '}' expected but eof found.
[INFO] [Console$] [error] }
[INFO] [Console$] [error]  ^
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/Preparator.scala:1: '{' expected but identifier found.
[INFO] [Console$] [error] package incubator-predictionio-template-similar-product
[INFO] [Console$] [error]                  ^
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/Preparator.scala:24: '}' expected but eof found.
[INFO] [Console$] [error] ) extends Serializable
[INFO] [Console$] [error]                       ^
[INFO] [Console$] [error] /Users/i.../MySimilarProduct/src/main/scala/Serving.scala:1: '{' expected but identifier found.
[INFO] [Console$] [error] package incubator-predictionio-template-similar-product
[INFO] [Console$] [error]                  ^
[INFO] [Console$] [error] /Users/.../MySimilarProduct/src/main/scala/Serving.scala:13: '}' expected but eof found.
[INFO] [Console$] [error] }
[INFO] [Console$] [error]  ^
[INFO] [Console$] [error] 12 errors found
[INFO] [Console$] [error] (compile:compile) Compilation failed
[INFO] [Console$] [error] Total time: 26 s, completed Oct 20, 2016 1:19:18 PM
[ERROR] [Console$] Return code of previous step is 1. Aborting.

**Comment by moein7tl** [comment]
I have the same error during building the recommendation engine

```
[INFO] [Console$] Using existing engine manifest JSON at /root/apache-predictionio-0.10.0-incubating/PredictionIO-0.10.0-incubating/bin/manifest.json
[WARN] [Template$] template.json does not exist. Template metadata will not be available. (This is safe to ignore if you are not working on a template.)
[INFO] [Console$] Using command '/root/apache-predictionio-0.10.0-incubating/PredictionIO-0.10.0-incubating/sbt/sbt' at the current working directory to build.
[INFO] [Console$] If the path above is incorrect, this process will fail.
[INFO] [Console$] Uber JAR disabled, but current working directory does not look like an engine project directory. Please delete lib/pio-assembly-0.10.0-incubating.jar manually.
[INFO] [Console$] Going to run: /root/apache-predictionio-0.10.0-incubating/PredictionIO-0.10.0-incubating/sbt/sbt  package assemblyPackageDependency
[INFO] [Console$] [info] Set current project to bin (in build file:/root/apache-predictionio-0.10.0-incubating/PredictionIO-0.10.0-incubating/bin/)
[INFO] [Console$] [warn] No main class detected
[INFO] [Console$] [success] Total time: 2 s, completed Apr 22, 2017 2:22:36 AM
[INFO] [Console$] [error] Not a valid command: assemblyPackageDependency
[INFO] [Console$] [error] Not a valid project ID: assemblyPackageDependency
[INFO] [Console$] [error] Expected ':' (if selecting a configuration)
[INFO] [Console$] [error] Not a valid key: assemblyPackageDependency (similar: sbtDependency)
[INFO] [Console$] [error] assemblyPackageDependency
[INFO] [Console$] [error]                          ^
[ERROR] [Console$] Return code of previous step is 1. Aborting.
```
